services:

  database:
    image: mariadb:10.6.4
    restart: unless-stopped
    env_file: .docker.env
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - 127.0.0.1:3307:3306
    networks:
      - hubbies-puppies-network

  api:
    build: .
    restart: unless-stopped
    user: 1000:1000
    depends_on:
      - database
    volumes:
      - ./app:/app
    networks:
      - hubbies-puppies-network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - ./app/public:/app/public
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 127.0.0.1:3000:80
    networks:
      - hubbies-puppies-network

networks:
  hubbies-puppies-network:

volumes:
  db-volume:
